steps:

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=cmd/dispatcher/Dockerfile
  - --destination=gcr.io/$PROJECT_ID/azure-event-channel-dispatcher:${COMMIT_SHA}
  - --destination=gcr.io/$PROJECT_ID/azure-event-channel-dispatcher:${_KANIKO_IMAGE_TAG}
  - --cache-repo=gcr.io/$PROJECT_ID/azure-event-channel-dispatcher/cache
  - --cache=${_KANIKO_USE_BUILD_CACHE}
  - --no-push=${_KANIKO_NO_PUSH}
  - ${_KANIKO_EXTRA_ARGS}
  waitFor: ['-']

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=cmd/controller/Dockerfile
  - --destination=gcr.io/$PROJECT_ID/azure-event-channel-controller:${COMMIT_SHA}
  - --destination=gcr.io/$PROJECT_ID/azure-event-channel-controller:${_KANIKO_IMAGE_TAG}
  - --cache-repo=gcr.io/$PROJECT_ID/azure-event-channel-controller/cache
  - --cache=${_KANIKO_USE_BUILD_CACHE}
  - --no-push=${_KANIKO_NO_PUSH}
  - ${_KANIKO_EXTRA_ARGS}
  waitFor: ['-']

timeout: 1800s

substitutions:
  _KANIKO_IMAGE_TAG: "latest"
  _KANIKO_NO_PUSH: "false"
  _KANIKO_USE_BUILD_CACHE: "true"
  _KANIKO_EXTRA_ARGS: ""

options:
  substitution_option: 'ALLOW_LOOSE'

tags:
  - azure-event-channel
