# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[override]]
  name = "github.com/knative/pkg"
  revision = "0851b95f902d3706fb842fe3160fb697bf5a60e1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.6"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.20.0"

[[constraint]]
  name = "github.com/Azure/azure-event-hubs-go"
  version = "1.3.1"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "32.5.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "13.0.0"

[[override]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  version = "0.9.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
