/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/triggermesh/azure-event-channel/pkg/apis/messaging/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureChannels implements AzureChannelInterface
type FakeAzureChannels struct {
	Fake *FakeMessagingV1alpha1
	ns   string
}

var azurechannelsResource = schema.GroupVersionResource{Group: "messaging.triggermesh.dev", Version: "v1alpha1", Resource: "azurechannels"}

var azurechannelsKind = schema.GroupVersionKind{Group: "messaging.triggermesh.dev", Version: "v1alpha1", Kind: "AzureChannel"}

// Get takes name of the azureChannel, and returns the corresponding azureChannel object, and an error if there is any.
func (c *FakeAzureChannels) Get(name string, options v1.GetOptions) (result *v1alpha1.AzureChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azurechannelsResource, c.ns, name), &v1alpha1.AzureChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureChannel), err
}

// List takes label and field selectors, and returns the list of AzureChannels that match those selectors.
func (c *FakeAzureChannels) List(opts v1.ListOptions) (result *v1alpha1.AzureChannelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azurechannelsResource, azurechannelsKind, c.ns, opts), &v1alpha1.AzureChannelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AzureChannelList{ListMeta: obj.(*v1alpha1.AzureChannelList).ListMeta}
	for _, item := range obj.(*v1alpha1.AzureChannelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureChannels.
func (c *FakeAzureChannels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azurechannelsResource, c.ns, opts))

}

// Create takes the representation of a azureChannel and creates it.  Returns the server's representation of the azureChannel, and an error, if there is any.
func (c *FakeAzureChannels) Create(azureChannel *v1alpha1.AzureChannel) (result *v1alpha1.AzureChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azurechannelsResource, c.ns, azureChannel), &v1alpha1.AzureChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureChannel), err
}

// Update takes the representation of a azureChannel and updates it. Returns the server's representation of the azureChannel, and an error, if there is any.
func (c *FakeAzureChannels) Update(azureChannel *v1alpha1.AzureChannel) (result *v1alpha1.AzureChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azurechannelsResource, c.ns, azureChannel), &v1alpha1.AzureChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureChannel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAzureChannels) UpdateStatus(azureChannel *v1alpha1.AzureChannel) (*v1alpha1.AzureChannel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(azurechannelsResource, "status", c.ns, azureChannel), &v1alpha1.AzureChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureChannel), err
}

// Delete takes name of the azureChannel and deletes it. Returns an error if one occurs.
func (c *FakeAzureChannels) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azurechannelsResource, c.ns, name), &v1alpha1.AzureChannel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureChannels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azurechannelsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AzureChannelList{})
	return err
}

// Patch applies the patch and returns the patched azureChannel.
func (c *FakeAzureChannels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AzureChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azurechannelsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AzureChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureChannel), err
}
